### PR TITLE
feat(network): install hosts and nss file in hostonly mode

### PR DESCRIPTION
**Pull request by ryncsn**
## Changes
Install hosts and nss file in hostonly initramfs can make it easier to
maintain the config and allow using hostname in initramfs stage.

## Checklist
- [x] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

### CODE REVIEW

**Comment by johannbg** [comment]
Meta modules should not contain hostonly sections so either this needs to be added to every networking module and or I can update the systemd-resolved module PR to include this.

**Comment by ryncsn** [comment]
I think it will be a good idea to include this in systemd-resolved.

**Comment by johannbg** [comment]
I might actually end up introducing nss module for the nss part of this

**Comment by haraldh** [comment]
Merged with   https://github.com/dracutdevs/dracut/pull/1378

**Pull request closed without merging**
