### PR TITLE
fips: Add new required module + cleanup

### PR DESCRIPTION
**Pull request by WOnder93**
This patchset adds `crypto_user` to the list of FIPS modules (needed by sha512hmac in Fedora 28+) and also cleans up the list of modules. See individual commit messages for more details.

### CODE REVIEW

**Comment by haraldh** [comment]
@centos-ci ok to test

**Comment by haraldh** [comment]
@centos-ci retest this, please

**Comment by t8m** [comment]
@WOnder93 Isn't it also necessary to modify the install() function to install .sha512hmac.hmac and the libkcapi.so.1 and .libkcapi.so.1.hmac?

Also the fipscheck should not be necessary on the inst_multiple line.
And:
``` inst_libdir_file libsoftokn3.so libsoftokn3.so \
         libsoftokn3.chk libfreebl3.so libfreebl3.chk \
         libssl.so 'hmaccalc/sha512hmac.hmac' libssl.so.10 \
         libfreeblpriv3.so libfreeblpriv3.chk
```
should be replaced with
``` inst_libdir_file libkcapi.so.1 .libkcapi.so.1.hmac
```

**Comment by WOnder93** [comment]
>Isn't it also necessary to modify the install() function to install .sha512hmac.hmac and the libkcapi.so.1 and .libkcapi.so.1.hmac?

@t8m Not really, the `dracut-install` helper already auto-detects library dependencies and also the `.hmac` files.

> Also the fipscheck should not be necessary on the inst_multiple line.

Yes, it is probably useless there, but this is a separate issue... I didn't want to remove things that I don't understand why they are there in the first place...

> ```
> inst_libdir_file libsoftokn3.so libsoftokn3.so \
>          libsoftokn3.chk libfreebl3.so libfreebl3.chk \
>          libssl.so 'hmaccalc/sha512hmac.hmac' libssl.so.10 \
>          libfreeblpriv3.so libfreeblpriv3.chk
> ```

I have no idea why any of that is in there (except of `'hmaccalc/sha512hmac.hmac'`, which is redundant anyway)... likely the whole block can be removed, but who knows...

**Comment by t8m** [comment]
OK, I do not say the unnecessary cruft must be removed in this PR. But it should be removed anyway - there is nothing using it anymore and the files from nss must not be pulled in as we do not want dracut to depend on nss.

**Comment by t8m** [comment]
Anything missing to merge this?

**Pull request merged**
