### PR TITLE
feat(systemd-initrd): add initrd-usr-fs.target

### PR DESCRIPTION
**Pull request by johannbg**
Adding a new systemd initrd-usr-fs.target to the systemd-initrd module

This pull request changes...

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

### CODE REVIEW

**Comment by haraldh** [comment]
```
❯ ls /usr/lib/systemd/system/initrd-usr-fs.target
ls: cannot access '/usr/lib/systemd/system/initrd-usr-fs.target': No such file or directory
```

**Comment by haraldh** [comment]
see also: https://github.com/systemd/systemd/blob/b5a80aa9d89cd82e53181cfd3288bba694622786/units/meson.build#L37

**Comment by johannbg** [comment]
@haraldh depends on systemd/systemd#19234 which I probably should have mentioned

**Comment by johannbg** [comment]
@haraldh the target has been merged upstream. 

See
https://github.com/systemd/systemd/blob/main/units/meson.build

And this for the whole PR that did it. 

https://github.com/systemd/systemd/commit/29a24ab28e9790680348b1ffab653a321fa49a67

**Pull request merged**
