### PR TITLE
ci: add Gentoo Linux container

### PR DESCRIPTION
**Pull request by LaszloGombos**
## Checklist
- [X] I have tested it locally
- [X] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

### CODE REVIEW

**Comment by johannbg** [comment]
@LaszloGombos what was the current status on this one?

**Comment by johannbg** [comment]
@LaszloGombos you need to fix your manifest as can be seen in the failing test :smile:  
Try include the full path in the FROM line in Dockerfile-Gentoo, for example instead of using `FROM gentoo/portage:latest` use `FROM docker.io/gentoo/portage:latest`
Btw is it better to use portage instead of the stage3 images for Gentoo?

**Comment by LaszloGombos** [comment]
> Try include the full path in the FROM line in Dockerfile-Gentoo,

Ok, updated the PR. Thanks for the hint !

**Comment by LaszloGombos** [comment]
Log of building the container to help with the reviews: https://github.com/dracutdevs/dracut/runs/7707115197
Also attached, as not sure about the retention policy
[log.txt](https://github.com/dracutdevs/dracut/files/9275943/log.txt)
.

**Comment by LaszloGombos** [comment]
CC @aafeijoo-suse to help with CI and/or move this PR forward somehow.

**Comment by aafeijoo-suse** [comment]
#1816 would be useful right now... :)

**Comment by aafeijoo-suse** [comment]
I found this useful tool which allows to locally test these kind of github actions: https://github.com/nektos/act

Although the docker tags look good, it throws the same error:
```
# act -j nosystemd
[Integration Test/nosystemd] Cannot parse container options: --privileged -v /dev:/dev
[Integration Test/nosystemd] 🚀  Start image=ghcr.io/dracutdevs/gentoo:latest
[Integration Test/nosystemd]   🐳  docker pull image=ghcr.io/dracutdevs/gentoo:latest platform= username= forcePull=false
[Integration Test/nosystemd] 🏁  Job succeeded
Error: Error response from daemon: manifest unknown
```

**Comment by LaszloGombos** [comment]
@aafeijoo-suse Thanks for helping out.

> Error: Error response from daemon: manifest unknown

I might not fully understand the full CI setup of this project, but I think the current CI is not prepared for PRs that changes container code - like this PR. 

I think the reason for the failure is because the new containers generation (container.yml) and running the test on the containers (integration.yml) runs paralel and integration will run earlier before the container is pushed to the registry. 

This is not a new problem and I have observed this in other PRs as well (e.g. https://github.com/dracutdevs/dracut/pull/1827). We had this problem for quite some time, and resolving this problem is outside of the scope of "introducing Gentoo container" PR.

Most importantly, after the PR lands and the container is pushed, subsequent CI runs and PRs would not have the test failing. 
 
TBH, this kind of PRs are so rare, that I am not sure if we want to address resolving this race in the CI system - lot of complexity for little benefit. 

One trivial work around is land the container code first and do the test integration PR later when the container is available - which is also the proposed approach on https://github.com/dracutdevs/dracut/pull/1827 

I will update this PR and just introduce the Gentoo container. Hope this will also make the review easier as the PR will be smaller.

**Comment by LaszloGombos** [comment]
not stale

**Review by johannbg — APPROVED** [review]

**Pull request merged**
