### PR TITLE
feat(github): automating dependency updates

### PR DESCRIPTION
**Pull request by johannbg**
This pull request changes...

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

### CODE REVIEW

**Review by LaszloGombos — APPROVED** [review]
lgtm. Thanks !

**Comment by johannbg** [comment]
@aafeijoo-suse ping for review, I think weekly means always on monday so we might want to change this to daily otherwise we need to wait a week for it to trigger.

**Comment by aafeijoo-suse** [comment]
> @aafeijoo-suse ping for review, I think weekly means always on monday so we might want to change this to daily otherwise we need to wait a week for it to trigger.

Yes, if you want another day you can add `day: "whatever"` after the interval row. See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleday

**Comment by johannbg** [comment]
@aafeijoo-suse added to morrow as the scheduler day so if we merge to day we see results tomorrow

**Review by aafeijoo-suse — APPROVED** [review]

**Comment by LaszloGombos** [comment]
Seems to fail ? - https://github.com/dracutdevs/dracut/runs/9069075284

**Pull request merged**
