### PR TITLE
Fix inconsistent variable use in 40network

### PR DESCRIPTION
**Pull request by mwilck**
## Changes

- fix(40network): consistent use of "$gw" for gateway

## Checklist
- [x ] I have tested it locally

Fixes #

### CODE REVIEW

**Review by johannbg — APPROVED** [review]
LGTM

**Review by gonzoleeman — APPROVED** [review]
Looks correct to me.

**Comment by mwilck** [comment]
Ping?

**Comment by johannbg** [comment]
@mwilck the project is in a bit of a bind at the moment, we have a strict 2 reviewers before merge ( otherwise I would have merged this already ) and I lack the necessary privileges to do override that. @haraldh has quit RH and has been busy in his new job and @danimo has also quit Suse and move to do other things. 

I had pinged Harald about replacing Daniel with @aafeijoo-suse that is if Antonio would have been interested in doing so as well as doing a release first I pinged Harald about that in September then again in December but no responses.

Meanwhile we have fixes for Suse,Fedora,Gentoo and Arch waiting to be merged ( or have been merged but wont hit downstream until we make a release, which Harald is the only person that can do so ).  

Harald kinda has to clarify what's going on and how he want's to proceed moving the project forward since he's the BDFL of the project.

**Comment by mwilck** [comment]
@johannbg, thanks for the update. Harald gone is obviously a difficult situation for dracut, sorry to hear this.

**Comment by johannbg** [comment]
@mwilck gone or just swamped in his new job/life, one can only speculate. 

I would think that if someone permanently leaves they would pass on the project to someone else just like Harald inherited dracut but then again Daniel did not remove himself from the reviewer list when he left so maybe leaving in silence is a German tradition atleast here, on these parts one would offboard himself if the intent was to leave.

**Comment by haraldh** [comment]
Sorry, swamped and needed a break from dracut.

**Comment by haraldh** [comment]
Gave @johannbg admin rights...
@lnykryn also has admin rights
Invited @aafeijoo-suse to dracutdevs and dracut

**Pull request merged**
