### PR TITLE
feat(tpm2-tss): introducing the tpm2-tss module

### PR DESCRIPTION
**Pull request by johannbg**
Introducing the tpm2-tss module. 

Note this depends on the udev global var PR so dont merge until after we have merged it.

This pull request changes...

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

### CODE REVIEW

**Comment by haraldh** [comment]
please add the following binaries:
```
            tpm2_pcrread tpm2_pcrextend tpm2_createprimary tpm2_createpolicy \
            tpm2_create tpm2_load tpm2_unseal 
```

**Review by haraldh — CHANGES_REQUESTED** [review]
please add the following binaries:
```
            tpm2_pcrread tpm2_pcrextend tpm2_createprimary tpm2_createpolicy \
            tpm2_create tpm2_load tpm2_unseal 
```

**Comment by haraldh** [comment]
Want to extend the `check()`??

**Comment by johannbg** [comment]
> Want to extend the `check()`??

Do we want to do that I mean those binaries are not part of upstream tpm2-tss module ( which is why I did not add them in the first place ) nor Fedora's tpm2-tss.  Now by adding them without adding them to check() section we get a "soft" dependcy as in those binaries are included if available but if not, the module can in sense just be used as an tpm2-tss "library" package.

But if you want them as a strict requirement ( as in they are always needed ) I can add them.

**Comment by johannbg** [comment]
@nullr0ute given that you are somewhat involved with the maintainership of tpm2 in Fedora, can you explain why the json files are being placed in /etc also the dbus files for the tpm2-abrmd component ( as opposed to under /usr ) ?

**Comment by nullr0ute** [comment]
> @nullr0ute given that you are somewhat involved with the maintainership of tpm2 in Fedora, can you explain why the json files are being placed in /etc also the dbus files for the tpm2-abrmd component ( as opposed to under /usr ) ?

No, I can't, TBH I've not looked at the tpm2-abrmd closely since it was dumped on me from the Intel maintainer, and generally abrmd isn't needed as generally these days you'll want to use the kernel resource manager at /dev/tpmrm0 rather than the userspace resource manager. I would definitely not be pulling abrmd into the initrd.

**Comment by nullr0ute** [comment]
> Introducing the tpm2-tss module.

What does this actually achieve/what's it used for?

**Comment by nullr0ute** [comment]
> Thanks for the heads up regarding abrmd I was wondering if I should create a module for that. What about those json file can we just skip them or are they being used by something in Fedora and or in the wild? ( this module would then just contain the libraries + tpm2 and it's links if available )

Any chance you could file a RHBZ and I'll take a look, don't have the cycles right now to dig into it. Generally none of the stuff I do with TPM2 in Fedora uses abrmd, it all uses the kernel resource manager.

**Comment by johannbg** [comment]
> > Introducing the tpm2-tss module.
> 
> What does this actually achieve/what's it used for?

Cryptsetups

**Comment by johannbg** [comment]
> > Thanks for the heads up regarding abrmd I was wondering if I should create a module for that. What about those json file can we just skip them or are they being used by something in Fedora and or in the wild? ( this module would then just contain the libraries + tpm2 and it's links if available )
> 
> Any chance you could file a RHBZ and I'll take a look, don't have the cycles right now to dig into it. Generally none of the stuff I do with TPM2 in Fedora uses abrmd, it all uses the kernel resource manager.

Dont waste your time digging into it. We will simply exclude the files and add them if and then when an RFE arrives for them.

**Review by haraldh — APPROVED** [review]

**Pull request merged**
