### PR TITLE
ci(suse.conf.example): update SUSE-specific config

### PR DESCRIPTION
**Pull request by aafeijoo-suse**
This pull request updates SUSE-specific config.
- Remove reference to mkinitrd.
- Update compression parameters.
- Remove explanatory code that is currently shipped in its own config file on SUSE. 

## Checklist
- [X] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

### CODE REVIEW

**Comment by LaszloGombos** [comment]
LGTM

**Comment by aafeijoo-suse** [comment]
.

**Comment by aafeijoo-suse** [comment]
.

**Comment by aafeijoo-suse** [comment]
2nd chance

**Review by johannbg — APPROVED** [review]
LGTM

**Review by LaszloGombos — APPROVED** [review]
LGTM

**Pull request merged**
