### PR TITLE
Make binutils optional when elfutils are available

### PR DESCRIPTION
**Pull request by danimo**
This is intended for minimum host OSes where 36 MB used by binutils
are deemed too expensive. We only need "strip", which exists as eu-strip
in elfutils, which in turn is < 1 MB in size.
    
 Note that the tests (TEST-04-FULL-SYSTEMD/test.sh) still depend on
 strip from binutils. It could use sstrip in the future.

### CODE REVIEW

**Comment by tpgxyz** [comment]
Looks interesting, i'll make some test on real hw.

**Comment by haraldh** [comment]
@centos-ci 
ok to test

**Comment by haraldh** [comment]
@centos-ci 
retest this

**Comment by haraldh** [comment]
@centos-ci 
 retest this please

**Pull request merged**
