### PR TITLE
fix(zfcp_rules): correct shellcheck regression when parsing ccw args

### PR DESCRIPTION
**Pull request by aafeijoo-suse**
## Checklist
- [X] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes 032ecd95c94b77f3f08237e0f765b355dacb9573

### CODE REVIEW

**Review by Vogtinator — APPROVED** [review]
Might be worth checking other places whether they got similarly broken.

**Comment by aafeijoo-suse** [comment]
> Might be worth checking other places whether they got similarly broken.

I agree

**Comment by aafeijoo-suse** [comment]
BTW this file will be removed by #2534, so I don't know if this fix makes sense upstream at this point.

**Review by tblume — APPROVED** [review]
LGTM

**Review by johannbg — APPROVED** [review]
LGTM

**Pull request merged**
