### PR TITLE
Generic SUSE patches

### PR DESCRIPTION
**Pull request by danimo**
These patches should not contain any SUSE specific changes (except
for SUSE-specific files already present in mainline). Most have been
around in production as patches on top of 044 for some time.

11 of them have already been posted by Thomas Renninger on the mailing
list, but have not been reviewed/merged so far.

If you prefer them in smaller PRs, I can try to further chunk this
down based on topics or by modules.

I will post others that required some adjustment to master separately.

### CODE REVIEW

**Comment by haraldh** [comment]
ok to test

**Comment by haraldh** [comment]
retest this please

**Comment by haraldh** [comment]
retest this please

**Comment by danimo** [comment]
Will submit in smaller chunks

**Pull request closed without merging**
