### PR TITLE
fix(kernel-network-modules): also install modules from mdio subdirectory

### PR DESCRIPTION
**Pull request by martinezjavier**
## Changes

A recent change in Linux kernel v5.10 split the MDIO drivers from the PHY
subdirectory into a new MDIO subdirectory [0]. This caused MDIO drivers
to not be included in the initramfs.

Also include the modules of this new subdirectory to prevent this issue.

[0]: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=a9770eac511

## Checklist
- [X] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

### CODE REVIEW

**Review by johannbg — APPROVED** [review]
You need to fix your commit msg to "fix(kernel-network-modules): also install modules from mdio subdirectory" to pass the commisery check otherwise LGTM

**Comment by martinezjavier** [comment]
> You need to fix your commit msg to "fix(kernel-network-modules): also install modules from mdio subdirectory" to pass the commisery check otherwise LGTM

Done. I just use the same subject prefix that was in the previous commit touching this file and assumed that was correct.

**Comment by johannbg** [comment]
@martinezjavier yep passes :beers:

**Comment by fda77** [comment]
Thanks @martinezjavier for the quick bugfix!

**Comment by fda77** [comment]
Thx @martinezjavier for the quick fix!

**Review by haraldh — APPROVED** [review]

**Pull request merged**
