### PR TITLE
feat(systemd-pcrphase): introducing the systemd-pcrphase module

### PR DESCRIPTION
**Pull request by johannbg**
This pull request changes...

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

### CODE REVIEW

**Comment by johannbg** [comment]
@aafeijoo-suse, @LaszloGombos ping for review.

**Review by aafeijoo-suse — COMMENTED** [review]
Don't we need to install `systemd-pcrphase-sysinit.service` as well? https://github.com/systemd/systemd/commit/047273e6

**Comment by johannbg** [comment]
> Don't we need to install `systemd-pcrphase-sysinit.service` as well?

Technically I dont think we need it ( if I read the docs right )  but yeah we should include it for completeness. I'll update the pr

**Comment by aafeijoo-suse** [comment]
> > Don't we need to install `systemd-pcrphase-sysinit.service` as well?
> 
> Technically I dont think we need it ( if I read the docs right ) but yeah we should include it for completeness. I'll update the pr

Right, it's a bit contradictory, while the commit message says `The "sysinit" one is placed between sysinit.target and basic.target.` (so, before dracut-pre-mount.service), the man page says that the initrd phase is covered by the systemd-pcrphase-initrd.service (enter-initrd/leave-initrd strings)...

**Review by aafeijoo-suse — APPROVED** [review]
systemd considers sysinit as "later boot", so this is fine.

**Review by LaszloGombos — APPROVED** [review]
lgtm

**Pull request merged**
