### PR TITLE
fix(lsinitrd.sh):  add a missing path to image

### PR DESCRIPTION
**Pull request by kenneth-dsouza**
Signed-off-by: Kenneth D'souza <kennethdsouza94@gmail.com>

This pull request changes...

## Checklist
- [x] I have tested it locally
- [x] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

### CODE REVIEW

**Comment by kenneth-dsouza** [comment]
Tested:
```
# rpm-ostree status
State: idle
AutomaticUpdatesDriver: Zincati
  DriverState: active; periodically polling for updates (last checked Tue 2022-12-13 15:26:52 UTC)
Deployments:
● fedora:fedora/x86_64/coreos/stable
                  Version: 37.20221106.3.0 (2022-11-28T20:05:48Z)
               BaseCommit: 6278bd1e5f311880a6975307e7ce734076a0b1a37f8a97c875c07037c748ddcc
             GPGSignature: Valid signature by ACB5EE4E831C74BB7C168D27F55AD3FB5323552A
                Initramfs: -I /etc/kd 

  fedora:fedora/x86_64/coreos/stable
                  Version: 36.20221030.3.0 (2022-11-11T15:51:02Z)
               BaseCommit: eab21e5b533407b67b1751ba64d83c809d076edffa1ff002334603bf13655a14
             GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
                Initramfs: -I /etc/kd 

# ./lsinitrd.sh | head
Image: /lib/modules/6.0.7-301.fc37.x86_64/initramfs.img: 74M
========================================================================
Early CPIO image
========================================================================
drwxr-xr-x   3 root     root            0 Jan  1  1970 .
-rw-r--r--   1 root     root            2 Jan  1  1970 early_cpio
drwxr-xr-x   3 root     root            0 Jan  1  1970 kernel
drwxr-xr-x   3 root     root            0 Jan  1  1970 kernel/x86
drwxr-xr-x   2 root     root            0 Jan  1  1970 kernel/x86/microcode
-rw-r--r--   1 root     root        32968 Jan  1  1970 kernel/x86/microcode/AuthenticAMD.bin
```

**Comment by aafeijoo-suse** [comment]
Regardless of this being accepted (I think `rpm-ostree` is specific to Fedora), first you need to fix the commit message. Read https://github.com/dracutdevs/dracut/blob/master/docs/HACKING.md#commit-messages and see some examples using `git log`.

**Comment by kenneth-dsouza** [comment]
@aafeijoo-suse  let me fix the commit message.

**Comment by kenneth-dsouza** [comment]
Can anyone help review this patch?

**Review by johannbg — CHANGES_REQUESTED** [review]
Can you change your commit message 
from 
`
fix(lsinitrd.sh): Add ostree default path for initramfs
`
to
`
fix(lsinitrd.sh): add a missing path to image
`
since initramfs.img is being used outside ostree as well so it's more of a general fix than an ostree specific one.

**Comment by kenneth-dsouza** [comment]
> Can you change your commit message from `fix(lsinitrd.sh): Add ostree default path for initramfs` to `fix(lsinitrd.sh): add a missing path to image` since initramfs.img is being used outside ostree as well so it's more of a general fix than an ostree specific one.

Sure, thanks for the feedback.

**Comment by kenneth-dsouza** [comment]
@johannbg ,  commit message has been changed, thanks.

**Review by johannbg — APPROVED** [review]

**Review by johannbg — APPROVED** [review]

**Pull request merged**
