### PR TITLE
fix graphics startup failure with the rhgb paramter in CentOS8.2

### PR DESCRIPTION
**Pull request by linux-gcc**
the bug occurs because the DRM (cirrus) driver for graphics card is not in the initrd.

### CODE REVIEW

**Comment by linux-gcc** [comment]
@haraldh can you help review this code?

**Comment by haraldh** [comment]
Well... https://github.com/dracutdevs/dracut/commit/ebeed55c073eeaf78b738fe2c91bb6327a2c3bfe

**Comment by haraldh** [comment]
Looks good to me

**Review by haraldh — APPROVED** [review]

**Comment by linux-gcc** [comment]
@haraldh thank you very much!  can this code merged into thre RHEL-8 branch? if this code be merged into the RHEL-8 branch,who should I contanct for operation. thanks!

**Comment by haraldh** [comment]
@lnykryn

**Comment by haraldh** [comment]
we should file this for master also

**Comment by linux-gcc** [comment]
@haraldh ok,thanks!

**Comment by linux-gcc** [comment]
please @lnykryn take the time to help merge code into RHEL-8 and master。thanks!

**Comment by linux-gcc** [comment]
When can this code be merged into RHEL-8 and master? @lnykryn @haraldh 

thanks!

**Comment by johannbg** [comment]
@linux-gcc technically you can go to edit on your pr and change the branch to master and I could merge it to the master branch since @haraldh has already reviewed and acked it which probably means that @lnykryn which handles the RHEL branches will probably have to cherry pick it from there or something. @danimo given that it's been a week from the PR and 4 days since it got reviewed and acked what's the usual SOP when handling this pull request applicable to multiple branches ( presumably you want this downstream for suse ) ?

**Comment by lnykryn** [comment]
Do we have any Bugzilla filed for this? And if not, can you please create one?
https://bugzilla.redhat.com/

**Comment by linux-gcc** [comment]
> Do we have any Bugzilla filed for this? And if not, can you please create one?
> https://bugzilla.redhat.com/
I have created the bugzila. url :https://bugzilla.redhat.com/show_bug.cgi?id=1874506
@lnykryn

**Comment by linux-gcc** [comment]
When can this code be merged into RHEL-8 and master?@lnykryn @haraldh @johannbg @danimo 

thanks!

**Comment by lnykryn** [comment]
For rhel8 it might take a while, it is late for 8.3 and there are some bureaucratic things I need to do before it will get to 8.4.

**Review by linux-gcc — COMMENTED** [review]
can you take the time to help review the code (dadfcc0)? 
@haraldh @johannbg @lnykryn @danimo

**Pull request closed without merging**
