### PR TITLE
fix(base): do not change the provided UUID

### PR DESCRIPTION
**Pull request by joshuacov1**
This was introduced by
https://github.com/dracutdevs/dracut/commit/d3532978de04c78f53664dad7b37705a49a7ee54
Bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=2012496

This pull request changes...

## Changes
During boot dracut parses the provided UUID to lower case and thus starts an endless loop wating for the devise to appear. The device is actually mapped correctly by the kernel (which doesn't tweak the UUID) but because we are waiting for a name with lower charachters the expeted device never appers which drops us at the emergency shell leaving the system unbootable.
This happens especially on nfts/fat filesystems because technically those don't have a UUID but searial numbers which are used by the linux tools as UUID.

## Checklist
- [x] I have tested it locally
- [x] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #
https://github.com/dracutdevs/dracut/issues/1635

### CODE REVIEW

**Comment by joshuacov1** [comment]
Any thoughts on this?
It actually breaks all boot processes when the squash.img (from live iso) is on vfat/ntfs partitions...

**Review by haraldh — APPROVED** [review]

**Review by johannbg — CHANGES_REQUESTED** [review]
Can you change your commit message 
from
`fix(dracut-lib.sh): do not change the provided UUID`
to
`fix(base): do not change the provided UUID`

**Comment by joshuacov1** [comment]
Done

> Can you change your commit message from `fix(dracut-lib.sh): do not change the provided UUID` to `fix(base): do not change the provided UUID`

**Comment by johannbg** [comment]
@joshuacov1 your commit msg still has `fix(dracut-lib.sh): do not change the provided UUID`

**Comment by joshuacov1** [comment]
It should be ok now.

I fetched master in the meantime and this updated the branch, but the last commit is the one to merge. 

> @joshuacov1 your commit msg still has `fix(dracut-lib.sh): do not change the provided UUID`

**Comment by johannbg** [comment]
@joshuacov1 ? As you can see the test is still failing and now you need to fix your commit message and squash all the new ones you just introduced with these actions into a single commit ...

**Comment by johannbg** [comment]
@joshuacov1 look at all the files that you are now changing, this cant be merged like this. It's probably best that you file a new PR at this point. One with the correct commit msg and only your changes and we close this PR.

**Comment by joshuacov1** [comment]
I'm sorry for the mess!

This is the new request:
https://github.com/dracutdevs/dracut/pull/1650

> @joshuacov1 look at all the files that you are now changing, this cant be merged like this. It's probably best that you file a new PR at this point. One with the correct commit msg and only your changes and we close this PR.

**Pull request closed without merging**
