### PR TITLE
respect bootdev when special devices are used

### PR DESCRIPTION
**Pull request by bcg62**
addressing #133

### CODE REVIEW

**Comment by haraldh** [comment]
ok to test

**Comment by haraldh** [comment]
ok to test

**Comment by bcg62** [comment]
closing in favor of this commit which is a better fix. 

https://github.com/dracutdevs/dracut/commit/e6ae0c61285a7ff2a5be88b276b8d0b309e0ba2e#diff-3dd6ccdf35e90073f28de0bb59976e4d

**Comment by haraldh** [comment]
Is this in master also? If not reopen

**Comment by bcg62** [comment]
cherry picked and re pushed.

**Comment by bcg62** [comment]
failing for echo -n, what's the background for this check? I see it in other modules.

**Comment by haraldh** [comment]
just use printf

**Comment by haraldh** [comment]
commit 5899f2f5163de4d68fbb35831e1f2230c22c71b3
Author: Mike Gilbert <floppym@gentoo.org>
Date:   Tue Jul 14 22:22:14 2015 -0400

    Replace echo -n with printf in code with a /bin/sh shebang
    
    POSIX does not mandate that echo support the -n parameter.
    printf has more well-defined behavior.

**Comment by haraldh** [comment]
@centos-ci 
retest this please

**Comment by bcg62** [comment]
are these valid failures?

**Comment by haraldh** [comment]
no.. let me rerun

**Comment by haraldh** [comment]
retest this please

**Comment by haraldh** [comment]
@centos-ci 
retest this please

**Comment by haraldh** [comment]
already merged

**Pull request closed without merging**
