### PR TITLE
ci: also run integration test on Ubuntu

### PR DESCRIPTION
**Pull request by bdrung**
## Changes

Add a Dockerfile for Ubuntu (very similar to Debian) and run the integration tests also on Ubuntu.

I built the container locally and tested that the test cases from the integration test succeed there.

## Checklist
- [x] I have tested it locally
- [x] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

### CODE REVIEW

**Review by aafeijoo-suse — COMMENTED** [review]
> The Ubuntu container is almost an exact copy of the Debian container.

+1

> Adding a new test container is a good time to discuss how we can we better maintain all of these test containers.

I'd love to see Ubuntu running on the CI, but adding a new container implies having to support it, we already have 5, and upstream resources (talking about people) are veeery limited...

**Comment by bdrung** [comment]
Added ubuntu to manialtest.

> I'd love to see Ubuntu running on the CI, but adding a new container implies having to support it, we already have 5, and upstream resources (talking about people) are veeery limited...

Ubuntu will use dracut-install in initramfs-tools (see [manual_add_modules is slow / consumes the most time](https://bugs.launchpad.net/ubuntu/+source/initramfs-tools/+bug/2031185)). So at least dracut-install will become part of Ubuntu main (see [[MIR] dracut](https://bugs.launchpad.net/ubuntu/+source/dracut/+bug/2031304)) and part of the 1000 packages our Ubuntu Foundations team will maintain.

**Review by aafeijoo-suse — APPROVED** [review]

**Comment by aafeijoo-suse** [comment]
Does this PR need to be merged before any of the Ubuntu tests go green?

**Comment by bdrung** [comment]
Yes, the Ubuntu tests need the Ubuntu container, which is only built from the master branch.

**Pull request merged**
