### PR TITLE
tests: Provide an rng device inside the vm

### PR DESCRIPTION
**Pull request by danimo**

### CODE REVIEW

**Comment by haraldh** [comment]
@centos-ci re-test please

**Comment by haraldh** [comment]
@centos-ci retest please

**Comment by haraldh** [comment]
@centos-ci retest this please

**Comment by danimo** [comment]
@centos-ci retest this please

**Comment by haraldh** [comment]
👍

**Comment by danimo** [comment]
@haraldh updated with the actual module load instructions.

**Pull request merged**
