### PR TITLE
￼ Remove obsolete prelinking functionality

### PR DESCRIPTION
**Pull request by danimo**

### CODE REVIEW

**Comment by haraldh** [comment]
```inst_multiple -o prelink``` is a NOP, if prelink is not existent anyway... I thought you want to remove  prelink from ```dracut.sh``` as well.

**Comment by danimo** [comment]
I didn't plan to remove prelinking entirely, but it's only consequent. Here you go :)

**Comment by danimo** [comment]
@centos-ci retest this please

**Comment by danimo** [comment]
@centos-ci retest this please

**Comment by haraldh** [comment]
@centos-ci retest this please

**Comment by haraldh** [comment]
@centos-ci retest this please

**Comment by danimo** [comment]
@centos-ci retest this please

**Pull request merged**
