### PR TITLE
fix(kernel-modules-extra): give warning messages rather than aborting

### PR DESCRIPTION
**Pull request by jiayi0118**
When installing module "90kernel-modules-extra", if non-existing files are found in modules.dep, give warning message and skip install these files, rather than aborting generating initramfs #1971

This pull request changes...

## Changes
Do not abort dracut when invalid files are found in modules.dep, just gives warning messages.

## Checklist
- [x] I have tested it locally
- [x] I have reviewed and updated any documentation if relevant
- [x] I am providing new code and test(s) for it

### CODE REVIEW

**Comment by johannbg** [comment]
What's the usecase for not exiting out if the user still needs regenerate the image after running depmod?

**Comment by jiayi0118** [comment]
Sometimes due to package uninstallation, some .ko modules are removed but there are residual records in the `modules.dep`, etc. It is okay to just skipped these non-existing .ko modules.

But it may be not enough to simply skip the non-existing .ko modules, thus the warning message to rerun `depmod` is also raised to remind users of more choices.

**Comment by johannbg** [comment]
@jiayi0118 why should we circumvent downstream packaging problem here upstream I mean why does not the package regenerate the module dependency list and initramfs image upon removal of said component?

**Comment by jiayi0118** [comment]
@johannbg This is because `dracut` may be used in a longtime work flow, and it is a little expensive that `dracut` aborts at somewhere the problem can just be avoided. On the other hand, of course it is better the module dependency is regenerated, this is why this patch will give more instructive warning to remind of users.

**Comment by johannbg** [comment]
@jiayi0118 we dont workaround downstream packaging issues here upstream and you have still not answered the question why the downstream package maintainer is not fixing his package to address this as what's technically preventing him from doing that also can you elaborate what a "longtime work flow" means?

**Comment by jiayi0118** [comment]
Of course the downstream package maintainers should fix their problems when the warning is given by dracut.

"longtime work flow" means some scenes that consume long time such as system upgrade, e.g. If dracut is called at the end of the process and aborts, the whole process will be re-executed.

Anyway, from my opinion it is both reasonable that dracut whether or not abort at this problem. My major advice is that whether dracut can give a more instructive warning message to indicate users what the problem is and guide them how to fix it.

**Pull request closed without merging**
