### PR TITLE
test(TEST-99-RPM): remove test

### PR DESCRIPTION
**Pull request by LaszloGombos**
Is there any interest to maintain this test ?

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
Probably would want to check with @pvalena and @lnykryn. I believe they rely on this test.

**Comment by LaszloGombos** [comment]
PR that disabled this test to run as part of integration test - https://github.com/dracutdevs/dracut/pull/1061 on Feb-2021..has not been run on CI since than..

**Comment by johannbg** [comment]
We are dropping package files so the answer to that would be nope but at the same time the argument can be made it can be dropped at the same time the spec file get dropped.

**Comment by LaszloGombos** [comment]
The test case is failing as it is - https://github.com/LaszloGombos/dracut/actions/runs/3452741015/jobs/5762849349 

If nobody is interested maintaining the this case, than what is the value of it ?

**Comment by johannbg** [comment]
@LaszloGombos zero value in it.

**Review by johannbg — APPROVED** [review]

**Review by aafeijoo-suse — APPROVED** [review]

**Pull request merged**
