### PR TITLE
Add timeout option to crypt module

### PR DESCRIPTION
**Pull request by Nicop06**
Please note that I did not test the feature with plymouth. If someone confirm
that it works I can update the pull-request accordingly.

### CODE REVIEW

**Comment by haraldh** [comment]
@centos-ci ok to test

**Comment by Nicop06** [comment]
It seems that this commit is breaking all the tests: https://github.com/dracutdevs/dracut-ci-centos/commit/234101a9c0835fa60d8bd175add0bc5ea6784212#diff-40161cd1a4593bf2e1e9490d6fe4d92b

**Comment by haraldh** [comment]
@centos-ci retest this, please

**Comment by haraldh** [comment]
@centos-ci retest this, please

**Comment by Nicop06** [comment]
@centos-ci retest this, please

**Comment by Nicop06** [comment]
Only admin can do that, right?

It seems that one of the hosts was unreachable when the test ran. I do not think this is due to my changes. Could you please restart the test to see if it works? Also, do I need to add tests for my features?

**Comment by Nicop06** [comment]
Any update on this PR? I think the tests are failing because of environment issues.

I have been running this code for more than 1 month on my laptop without any issue. I use it to shutdown my laptop if no password is entered.

**Pull request merged**
