### PR TITLE
95iscsi: Replace iscsistart with iscsid

### PR DESCRIPTION
**Pull request by danimo**
This allows to setup multiple paths to targets, which is
required for iscsi multipath.

### CODE REVIEW

**Comment by haraldh** [comment]
```
+ make syncheck
modules.d/95iscsi/iscsiroot.sh contains [[
```

**Comment by danimo** [comment]
@centos-ci retest this, please

**Comment by haraldh** [comment]
@centos-ci retest this, please

**Comment by haraldh** [comment]
@centos-ci retest this, please

**Comment by haraldh** [comment]
@centos-ci retest this, please

**Comment by haraldh** [comment]
@centos-ci retest this, please

**Comment by haraldh** [comment]
Pushed a slightly modified version. Please review.

Notably, I had to remove:
```
-    if iscsiadm -m node; then
-        targets=$(iscsiadm -m node | sed 's/^.*iqn/iqn/')
-    else
```
because otherwise, it would not connect to multiple targets found on different networks, as soon as they come online.

**Pull request closed without merging**
