### PR TITLE
Fix ima evm

### LINKED ISSUE #1847: 98integrity: EVM is always enabled, even when there are no EVM keys
**Describe the bug**
The code in `98integrity/evm-enable.sh` is always enabling EVM, even when the /etc/keys/evm directory is missing or present but empty.

This is because in both cases (missing or empty), the `for` loop in `load_evm_x509` will assign for `PUBKEY` a value (usually `/sysroot/etc/keys/evm/*`).  In POSIX shell if the directory is missing or empty, the expansion will no happen and the iteration variable will have the full path (instead of empty, as one should expect from other languages).

Eventually this will make the function to return 0, and consider that some key has been loaded, and finally write 2 in `/sys/kernel/security/evm`.

**Distribution used**
openSUSE Tumbleweed

**Dracut version**
HEAD

**To Reproduce**
Install dracut and enable the "integrity" module. Make sure that /etc/keys/evm is missing (default) or empty. Create the initrd and check the content of "/sys/kernel/security/evm", if is different from 0 the bug is present.

**Expected behavior**
EVM should not be enabled if there are not keys available in /etc/keys/evm.

### PR DESCRIPTION
**Pull request by aplanas**
This pull request changes...

## Changes

* Drop unused variable
* Do not enable EVM if there are no key in the system

## Checklist
- [X] I have tested it locally
- [X] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #1847

### CODE REVIEW

**Review by aafeijoo-suse — CHANGES_REQUESTED** [review]
@aplanas, you need to change the commit messages to make the checker happy:

- `fix(integrity): do not enable EVM if there is no key`
- `fix(integrity): remove unused variable`

**Comment by aafeijoo-suse** [comment]
CC @stefanberger

**Comment by aplanas** [comment]
> @aplanas, you need to change the commit messages

Done, thanks!

**Comment by stefanberger** [comment]
LGTM.

**Review by johannbg — APPROVED** [review]
LGTM

**Review by aafeijoo-suse — APPROVED** [review]
LGTM

**Pull request merged**
