### PR TITLE
dracut: don't refuse root=tmpfs when systemd is used

### PR DESCRIPTION
**Pull request by poettering**
A match for systemd https://github.com/systemd/systemd/pull/18847

This pull request changes...

## Checklist
- [ x ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

### CODE REVIEW

**Review by johannbg — APPROVED** [review]
LGTM

**Comment by johannbg** [comment]
@poettering since the github app does not show failed test I missed this. Anyway you need to fix your commit msg to pass the commisery check. Change it to ```fix(dracut-systemd): don't refuse root=tmpfs when systemd is used```

**Review by johannbg — CHANGES_REQUESTED** [review]
Fails commisery check...

**Comment by poettering** [comment]
force pushed new version. only change is the commit msg fix

**Review by johannbg — APPROVED** [review]

**Review by danimo — APPROVED** [review]

**Pull request merged**
