### PR TITLE
dracut-functions.sh:get_persistent_dev() use persistent_policy

### PR DESCRIPTION
**Pull request by haraldh**
set a default value for persistent_policy and let persistent_policy
control on how dracut references a device.

### CODE REVIEW

**Comment by haraldh** [comment]
ok to test

**Comment by haraldh** [comment]
retest this please

**Comment by mwilck** [comment]
@haraldh, again, this will not work as intended.
```
+    for j in ${persistent_policy[@]}; do
+	for i in /dev/disk/${i}/*; do

...
+persistent_policy+=( mapper by-uuid by-label by-partuuid by-partlabel by-id by-path )
```
The above code will check `/dev/disk/mapper` and will never find a match. I can propose a fix if you want.

**Comment by haraldh** [comment]
@mwilck I know.. sorry.. I misused this PR to do some CI testing.. I will not merge this unfixed.

**Comment by mwilck** [comment]
I sent you a [pull request](https://github.com/haraldh/dracut/pull/1) for haraldh/dracut/persistent_policy where this should work fine now.

**Pull request closed without merging**
