### PR TITLE
test: improve infrastructure and coverage

### PR DESCRIPTION
**Pull request by LaszloGombos**
Series of commits to improve testing infrastructure.
None of these commits changes any of the dracut functionality for existing modules.
Goal is to improve portability of tests and code coverage.
It is also a goal to move more execution to dracut command line to improve code coverage.
Sharing more code between test cases would allow to remove about 50 lines of source code from each test case.

Changes are to to TEST-03-USR-MOUNT only as part of this PR to demonstrate the benefits and confirm that there is no regression. Plan to change other TEST as a follow-up PR. 

Picked TEST-03-USR-MOUNT as it is one of our simplest and most portable test that is most unlikely to interfere with other open PRs.

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [X] I am providing new code and test(s) for it

### CODE REVIEW

**Comment by LaszloGombos** [comment]
All check passed, plan to stop the work here for this PR.

**Review by johannbg — APPROVED** [review]
LGTM

**Comment by johannbg** [comment]
> All check passed, plan to stop the work here for this PR.

Just a workflow pointer. 

It's better, more efficient and more visible if PR's that are still being worked on, are put into draft status with WIP: ( like you can see I have done in few places ) and taken out of draft status when the PR is ready.

**Review by aafeijoo-suse — APPROVED** [review]

**Comment by aafeijoo-suse** [comment]
@LaszloGombos great job here, thanks!

**Pull request merged**
