### PR TITLE
90multipath: minor tweaks to multipathd-configure.service

### PR DESCRIPTION
**Pull request by jlebon**
Noticed these while perusing this code. I don't think it's currently causing any issues, other than added confusion. :)

See individual commits.

### CODE REVIEW

**Comment by bmarzins** [comment]
Both of these changes look correct to me.

**Review by miabbott — APPROVED** [review]

**Comment by miabbott** [comment]
Oops, thought I was in a different repo...treat my approval accordingly  :stuck_out_tongue:

**Comment by jlebon** [comment]
Can we get this in?

**Review by johannbg — APPROVED** [review]
LGTM

**Pull request merged**
