### PR TITLE
95fcoe: don't install if there is no FCoE hostonly devices

### PR DESCRIPTION
**Pull request by ryncsn**
## Changes
When in hostonly mode, 95fcoe module will still be installed even there
is no FCoE hostonly device. So use the new block_is_fcoe helper to check
for hostonly device in hostonly mode, avoid installing unneccessary module.

## Checklist
- [x] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

### CODE REVIEW

**Comment by ryncsn** [comment]
Hi, @danimo , I saw in commit 480aa9695 you added this helper block_is_fcoe, but left a comment:
# block_is_fcoe <maj:min>
# Check whether $1 is an FCoE device
# Will not work for HBAs that hide the ethernet aspect
# completely and present a pure FC device

I'm not sure about the case that the ethernet aspect is hidden, in such cases, will the original FCoE detection logic in 95fcoe (check if "/sys/bus/fcoe/devices/ctlr_*" exists) work? And in that case, is the 95fcoe module still needed?

**Comment by danimo** [comment]
> Hi, @danimo , I saw in commit [480aa96](https://github.com/dracutdevs/dracut/commit/480aa9695f8c2e2b30c8f41ae8483140020d23db) you added this helper block_is_fcoe, but left a comment:
> 
> block_is_fcoe maj:min
> Check whether $1 is an FCoE device
> Will not work for HBAs that hide the ethernet aspect
> completely and present a pure FC device
> 
> I'm not sure about the case that the ethernet aspect is hidden, in such cases, will the original FCoE detection logic in 95fcoe (check if "/sys/bus/fcoe/devices/ctlr_*" exists) work? And in that case, is the 95fcoe module still needed?

Our storage department told me that those adapters appear as if they were local block storage HBAs, so the FCoE aspect is completely hidden from the operating system and thus the 95fcoe module is not needed. If there are modules that have an inbetween behavior, the current logic should be good enough to detect whether or not to include the module.

**Comment by danimo** [comment]
Based on that information, do you want me to merge the PR?

**Comment by ryncsn** [comment]
Thanks for the info, I think it's OK to merge it.

**Pull request merged**
