### PR TITLE
feat(fs-lib): make gentoo container pass test-01

### LINKED ISSUE #1952: consistent mapping of LABEL/UUID to devices
We have two functions mapping LABEL/UUID to devices. One of them is exact match (label_uuid_to_dev) and it is used in most modules.

There is however an other function that does fuzzy matching and returns with a _list_ of devices (devnames). This is to allow to be sloppy with LABEL/UUID and allow for e.g. "UUID=123" device specification.

fstab_mount might end up running  fsck_single on a different device than the actual device that is being mounted.

I suggest to only use devnames in crypt-lib.sh and stick to label_uuid_to_dev on all other cases.

devnames does NOT support PARTLABEL nor PARTUUID, which is supported by label_uuid_to_dev.

### PR DESCRIPTION
**Pull request by LaszloGombos**
## Checklist
- [X] I have tested it locally
- [X] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #1952 #2091

### CODE REVIEW

**Comment by LaszloGombos** [comment]
not stale

**Review by aafeijoo-suse — APPROVED** [review]

**Comment by LaszloGombos** [comment]
This PR changes a function that is only called if systemd is not in initramfs.

This issue seem to impact Gentoo container passing test 01 (as it does not have systemd installed).

Full test run - https://github.com/LaszloGombos/dracut/actions/runs/3451869106/jobs/5761388877

**Comment by johannbg** [comment]
Did you forget to update your commit message by any chance?

**Comment by LaszloGombos** [comment]
Gentoo passing (with this PR) - https://github.com/LaszloGombos/dracut/actions/runs/3453311170/jobs/5763808493
Gentoo failing (without this PR) - https://github.com/dracutdevs/dracut/actions/runs/3453323734/jobs/5763829434

**Comment by LaszloGombos** [comment]
@johannbg I will stop assigning if it is not useful. This is to help issues that are already reviewed by one person and need the second review. You can use https://github.com/dracutdevs/dracut/issues?q=is%3Aopen+assignee%3A%40me to quickly find them in the review queue. But if not useful, I will stop.

**Comment by johannbg** [comment]
You never assign issues to individuals without discussing it with the relevant individuals before, be it your dayjob or F/OSS projects. We use what was design for this, which is labels and the label should be 'needs reviewing'

**Review by johannbg — APPROVED** [review]

**Pull request merged**
