### PR TITLE
Enable the use of the OverlayFS for the LiveOS root filesystem.

### PR DESCRIPTION
**Pull request by FGrose**
Integrate the option to use an OverlayFS as the root filesystem
into the 90dmsquash-live module for testing purposes.

The rd.live.overlay.overlayfs option allows one to request an
OverlayFS overlay.  If a persistent overlay is detected at the
standard LiveOS path, the overlay & type detected will be used.

Tested primarily with transient in-RAM overlay boots on vfat-
formatted Live USB devices, with persistent overlay directories
on ext4-formatted Live USB devices, and with embedded, persistent
overlay directories on vfat-formatted devices. (Persistent overlay
directories on a vfat-formatted device must be in an embedded
filesystem that supports the creation of trusted.\* extended attributes,
and must provide valid d_type in readdir responses.)

The rd.live.overlay.readonly option, which allows a persistent
overlayfs to be mounted read only through a higher level transient
overlay directory, has been implemented through the multiple lower
layers feature of OverlayFS.

~~This implementation currently requires the enforcing=0 kernel command
line option.  Further SELinux tuning may change this limitation.~~
(SELinux is supported in OverlayFS since kernel 4.8.)

The default transient DM overlay size has been adjusted up to 32 GiB.
This change supports comparison of transient Device-mapper vs.
transient OverlayFS overlay performance.  A transient DM overlay
is a sparse file in memory, so this setting does not consume more
RAM for legacy applications.  It does permit a user to use all of
the available root filesystem storage, and fails gently when it is
consumed, as the available free root filesystem storage on a typical
LiveOS build is only a few GiB.  Thus, when booted on other-
than-small RAM systems, the transient DM overlay should not overflow.

OverlayFS offers the potential to use all of the available free RAM
or all of the available free disc storage (on non-vfat-devices)
in its overlay, even beyond the root filesystem available space,
because the OverlayFS root filesystem is a union of directories on
two different partitions.

### CODE REVIEW

**Comment by FGrose** [comment]
Mailing list post: http://article.gmane.org/gmane.linux.kernel.initramfs/4308

**Comment by bcl** [comment]
This is worth exploring, but if it can't support SELinux it can't be used for live installations. We also need to make sure that /dev/mapper/live-base or something similar points to the original base filesystem so that local changes don't get copied to the target during installation.

**Comment by FGrose** [comment]
This version continues to provide `/dev/mapper/live-base` even with the `rd.live.overlay.overlayfs` option in order to be compatible with the current installation structures.  Some users may eventually want to avoid any Device-mapper overhead, and the OverlayFS does depend on the read-only base image, `ext3fs.img` or `rootfs.img`, mounted at `/run/rootfsbase`.

The purpose of this version is to provide a means to optionally boot an OverlayFS version of LiveOS in Fedora Rawhide so that others can test its features and limitations, with the hope that those with expertise in SELinux and other affected components could explore adaptations to complete the integration.

**Comment by haraldh** [comment]
ok to test

**Comment by Conan-Kudo** [comment]
@bcl @FGrose My understanding is that this should work with SELinux now? I think Dan Walsh made it work in recent kernels so that Docker+SELinux+OverlayFS worked.

**Comment by haraldh** [comment]
@centos-ci 
ok to test

**Comment by haraldh** [comment]
@centos-ci
retest this please

**Comment by FGrose** [comment]
I forced pushed amended commits to simplify checking the overlayfs commandline argument for those cases where only one check is needed.

**Comment by FGrose** [comment]
I force pushed a couple of fixes: 1. to better deal with the readonly_overlay code path for OverlayFS, and 2. to take advantage of the $sz variable while setting up live-osimg-min.
Here was the diff:
```shell
diff --git a/modules.d/90dmsquash-live/dmsquash-live-root.sh b/modules.d/90dmsquash-live/dmsquash-live-root.sh
index 987065b..60ef6c1 100755
--- a/modules.d/90dmsquash-live/dmsquash-live-root.sh
+++ b/modules.d/90dmsquash-live/dmsquash-live-root.sh
@@ -164,13 +164,15 @@ do_live_overlay() {
 
     # set up the snapshot
     sz=$(blockdev --getsz $BASE_LOOPDEV)
-    if [ -n "$readonly_overlay" ]; then
-        echo 0 $sz snapshot $BASE_LOOPDEV $OVERLAY_LOOPDEV P 8 | dmsetup create --readonly live-ro
-        base="/dev/mapper/live-ro"
-        over=$RO_OVERLAY_LOOPDEV
-    else
-        base=$BASE_LOOPDEV
-        over=$OVERLAY_LOOPDEV
+    if [ -z "$overlayfs" ]; then
+        if [ -n "$readonly_overlay" ]; then
+            echo 0 $sz snapshot $BASE_LOOPDEV $OVERLAY_LOOPDEV P 8 | dmsetup create --readonly live-ro
+            base="/dev/mapper/live-ro"
+            over=$RO_OVERLAY_LOOPDEV
+        else
+            base=$BASE_LOOPDEV
+            over=$OVERLAY_LOOPDEV
+        fi
     fi
 
     if [ -n "$thin_snapshot" ]; then
@@ -295,7 +297,7 @@ fi
 if [ -b "$OSMIN_LOOPDEV" ]; then
     # set up the devicemapper snapshot device, which will merge
     # the normal live fs image, and the delta, into a minimzied fs image
-    echo "0 $( blockdev --getsz $BASE_LOOPDEV ) snapshot $BASE_LOOPDEV $OSMIN_LOOPDEV P 8" | dmsetup create --readonly live-osimg-min
+    echo "0 $sz snapshot $BASE_LOOPDEV $OSMIN_LOOPDEV P 8" | dmsetup create --readonly live-osimg-min
 fi
 
 ROOTFLAGS="$(getarg rootflags)"
@@ -306,8 +308,8 @@ fi
 if [ -n "$overlayfs" ]; then
     mkdir -m 0755 /run/rootfsbase
     if [ -n "$reset_overlay" ] && [ -L /run/overlayfs ]; then
-        rm -r -- $(readlink /run/overlayfs)
-        mkdir -m 0755 $(readlink /run/overlayfs)
+        ovlfs=$(readlink /run/overlayfs)
+        rm -r -- ${ovlfs}/* ${ovlfs}/.*
     fi
     if [ -n "$readonly_overlay" ]; then
         mkdir -m 0755 /run/rootfsbase-r
```

**Comment by haraldh** [comment]
``` rm -r -- ${ovlfs}/* ${ovlfs}/.*```

Wouldn't that lead to error messages like:
```
rm: refusing to remove '.' or '..' directory: skipping […]
rm: refusing to remove '.' or '..' directory: skipping […]
```

**Comment by haraldh** [comment]
@centos-ci 
retest please

**Comment by haraldh** [comment]
@centos-ci
retest this please

**Comment by FGrose** [comment]
@haraldh re: `rm -r -- ${ovlfs}/* ${ovlfs}/.*`  -- Yes, 2 message lines in several pages.  This version drops them into `/dev/null`.

I've force pushed a couple more fixes: 1. to deal properly with a missing OverlayFS overlay, and 2. to die if 'rd.live.overlay.overlayfs' is specified with a Device-mapper overlay file.
The diff from before is the following:
```patch
diff --git a/usr/lib/dracut/modules.d/90dmsquash-live/dmsquash-live-root.sh b/modules.d/90dmsquash-live/dmsquash-live-root.sh
index 6a5d0c2..27ef3a7 100755
--- a/usr/lib/dracut/modules.d/90dmsquash-live/dmsquash-live-root.sh
+++ b/modules.d/90dmsquash-live/dmsquash-live-root.sh
@@ -119,7 +119,10 @@ do_live_overlay() {
             umount -l /run/initramfs/overlayfs || :
             oltype=$(det_img_fs $OVERLAY_LOOPDEV)
             if [ $oltype = DM_snapshot_cow ]; then
-                if [ -n "$reset_overlay" ]; then
+                if [ -n "$overlayfs" ]; then
+                    die "Found a Device-mapper overlay--not OverlayFS... " \
+                        "rd.live.overlay.overlayfs is not valid."
+                elif [ -n "$reset_overlay" ]; then
                     dd if=/dev/zero of=$OVERLAY_LOOPDEV bs=64k count=1 conv=fsync 2>/dev/null
                 fi
             else
@@ -131,7 +134,7 @@ do_live_overlay() {
             ln -s /run/initramfs/overlayfs$pathspec /run/overlayfs$opt
             ln -s /run/initramfs/overlayfs$pathspec/../ovlwork /run/ovlwork$opt
         fi
-        setup="yes"
+        blkid $OVERLAY_LOOPDEV >/dev/null 2>&1 || [ -d "/run/overlayfs$opt" ] && setup="yes"
     fi
     if [ -n "$overlayfs" ]; then
         modprobe overlay
@@ -309,7 +312,7 @@ if [ -n "$overlayfs" ]; then
     mkdir -m 0755 /run/rootfsbase
     if [ -n "$reset_overlay" ] && [ -L /run/overlayfs ]; then
         ovlfs=$(readlink /run/overlayfs)
-        rm -r -- ${ovlfs}/* ${ovlfs}/.*
+        rm -r -- ${ovlfs}/* ${ovlfs}/.* >/dev/null 2>&1
     fi
     if [ -n "$readonly_overlay" ]; then
         mkdir -m 0755 /run/rootfsbase-r
(END)
```

**Comment by FGrose** [comment]
This rebased commit accomplishes the OverlayFS feature and includes the fixes from pull request #190, superseding it, if this commit is accepted.

See also some testing of `sudo dnf upgrade` on a LiveOS with OverlayFS at issue #104.

**Comment by haraldh** [comment]
@centos-ci
retest this please

**Comment by Conan-Kudo** [comment]
@FGrose @haraldh How does this look now?

**Comment by haraldh** [comment]
@centos-ci
retest this please

**Comment by FGrose** [comment]
Added documentation for the OverlayFS overlays.

Added feedback for missing overlays.   But I couldn't find a more generic test for an active plymouth splash, such as rhgb, in the DRACUT_SYSTEMD case.

I also tried
`systemd-ask-password --timeout=0 message`, but the rhgb case fails to show the message prompt (a bug, I think, in plymouth). If I could sendkey <Esc>, this would show the startup console.

I also tried
```sh
cat > /run/systemd/ask-password/ask.0000<<EOF
[Ask]
Socket=/dev/null
Message=${m[*]}
timeout=0
EOF
```
but the message is limited to a single line and the notification doesn't pause and is lost in a lot of other messages at the startup console.

**Comment by Conan-Kudo** [comment]
@haraldh It looks like the current test failures are not related to this PR, and the latest test run in master appears to be broken on the same tests.

At this point, could you consider it acceptable to merge so that it could be available in Fedora 26? @FGrose has prepared changes for my project (livecd-tools) to be able to leverage overlayfs for live media, and I'd like to pull that in and make it available for livecd-tools v26.

**Comment by haraldh** [comment]
tested locally and pushed manually

**Comment by FGrose** [comment]
See pull request #217 for a fix needed for newer mount utilities on Fedora 26.

**Pull request merged**
