### PR TITLE
Initial Stratis support

### PR DESCRIPTION
**Pull request by tasleson**
Ref. https://github.com/stratis-storage

Signed-off-by: Tony Asleson <tasleson@redhat.com>

### CODE REVIEW

**Comment by haraldh** [comment]
why don't you use systemd units for the daemon?

**Comment by tasleson** [comment]
@haraldh Thanks, will look into using that instead

**Comment by haraldh** [comment]
now squash your commits and I will merge them

**Comment by tasleson** [comment]
> now squash your commits and I will merge them

Done, thanks!

**Pull request merged**
