### PR TITLE
fix: move ldconfig after library workaround

### PR DESCRIPTION
**Pull request by puleglot**
This fixes boot failures when libgcc_s.so.1 is in a non-standard
directory.

Bug: https://bugs.gentoo.org/760249
Fixes: de3cb0e3214c (dracut.sh: Move the library workaround after squash)

This pull request changes...

## Checklist
- [x] I have tested it locally
- [x] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

### CODE REVIEW

**Review by haraldh — APPROVED** [review]

**Review by johannbg — APPROVED** [review]
LGTM

**Review by danimo — APPROVED** [review]

**Comment by johannbg** [comment]
@puleglot You need to rebase and fix your commit msg before we can merge this

**Comment by danimo** [comment]
@puleglot ping?

**Comment by danimo** [comment]
You also need to use the new format for commits or the bot will fail, see https://github.com/dracutdevs/dracut/blob/master/HACKING.md.

**Pull request merged**
