### PR TITLE
Make externally defined CFLAGS work

### PR DESCRIPTION
**Pull request by danimo**
This is required by some distributions such as openSUSE
That define alternate cflags, rather than just appending
new ones.

### CODE REVIEW

**Comment by haraldh** [comment]
Huh? What about KMOD_CFLAGS?

**Comment by haraldh** [comment]
We could also merge the two `CFLAGS`

**Comment by danimo** [comment]
Like this?
```
override CFLAGS = -O2 -g -Wall -std=gnu99 -D_FILE_OFFSET_BITS=64 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2
CFLAGS += $(KMOD_CFLAGS)
```

**Comment by haraldh** [comment]
what's wrong with `?=`

**Comment by danimo** [comment]
Good point. But agree with the rest?

**Comment by haraldh** [comment]
```
CFLAGS ?= -O2 -g -Wall -std=gnu99 -D_FILE_OFFSET_BITS=64 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2
CFLAGS += $(KMOD_CFLAGS)
```

**Comment by danimo** [comment]
This works for me now.

**Pull request merged**
