### PR TITLE
ci: release

### LINKED ISSUE #2416: Use Github Actions to make a release
I recommend using https://github.com/softprops/action-gh-release to automate the release process. 

The step described in https://github.com/dracutdevs/dracut/blob/master/docs/RELEASE.md can be automated using Github Action.

Here is a short outline on what I am thinking.

```
apt install cargo                                                                                                                                                                         
cargo install clog-cli                                                                                                                                                                            
clog -F                                                                                                                                                                                           
make CONTRIBUTORS >> NEWS.md                                                                                                                                                                      
make AUTHORS                                                                                                                                                                                      
git commit -m "docs: update NEWS.md and AUTHORS" NEWS.md AUTHORS    
```

### PR DESCRIPTION
**Pull request by Henrik66**
This pull request allows making a release using a Github Action.

I tested it on my personal fork. 

This is how a release page turned out - https://github.com/Henrik66/dracut/releases/tag/060

This is the commit the release process generated - https://github.com/Henrik66/dracut/commit/d340ceaef2276b4dba8217967f1340510a0974b7

Fixes #2416

### CODE REVIEW

**Review by aafeijoo-suse — COMMENTED** [review]
I miss the contributors list in your test release: https://github.com/Henrik66/dracut/releases/tag/060 (see https://github.com/dracutdevs/dracut/releases/tag/057). Is it expected?

**Comment by Henrik66** [comment]
> I miss the contributors list in your test release: https://github.com/Henrik66/dracut/releases/tag/060 (see https://github.com/dracutdevs/dracut/releases/tag/057). Is it expected?

Thanks you @aafeijoo-suse . No this is not expected. I missed it and now corrected it.

**Comment by Henrik66** [comment]
> Thanks! Can you confirm that the "Dracut Release Bot" is not creating a duplicate release entry in NEWS.md?
> 
> * [Henrik66@3f2cf80](https://github.com/Henrik66/dracut/commit/3f2cf804a8c084971b6bf43507d6165e91ad1d2b)
> * [Henrik66@dd26236](https://github.com/Henrik66/dracut/commit/dd26236b5ca8ce91ae9ad5e242432302b5b02000)

Sorry for the confusion. I think the 2 commits were because of my debugging.

I reapplied the PR and re-run the release generation, which lead to a clean commit history.

https://github.com/Henrik66/dracut/commit/472c839c3dfcf70a90b02091d80ca49ba1617c7f

**Review by aafeijoo-suse — APPROVED** [review]
> Sorry for the confusion. I think the 2 commits were because of my debugging.
> 
> I reapplied the PR and re-run the release generation, which lead to a clean commit history.
> 
> [Henrik66@472c839](https://github.com/Henrik66/dracut/commit/472c839c3dfcf70a90b02091d80ca49ba1617c7f)

No problem, thanks!

**Pull request merged**
