### PR TITLE
ci: fix Arch container

### PR DESCRIPTION
**Pull request by LaszloGombos**
packages should be installed with -Syu instead of -Sy.

## Checklist
- [X] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

### CODE REVIEW

**Comment by LaszloGombos** [comment]
The scheduled container generation started to fail on Nov-5
https://github.com/dracutdevs/dracut/actions/runs/3399901041/jobs/5653953626

It was building on Nov-4
https://github.com/dracutdevs/dracut/actions/runs/3393451785/jobs/5640805180

**Comment by LaszloGombos** [comment]
From https://wiki.archlinux.org/title/pacman

> ...do not run pacman -Sy package_name instead of pacman -Syu package_name, as this could lead to dependency issues.

**Review by johannbg — APPROVED** [review]

**Review by aafeijoo-suse — APPROVED** [review]

**Comment by aafeijoo-suse** [comment]
@LaszloGombos unrelated, but Dockerfile-Gentoo took 55 minutes to finish...

**Comment by LaszloGombos** [comment]
> @LaszloGombos unrelated, but Dockerfile-Gentoo took 55 minutes to finish...

That is expected. It used to be over 3 hours before https://github.com/dracutdevs/dracut/commit/11eef2cfd2349dcf0a0d872e759c6c71e85e89aa landed. 

This is only for PRs that change Dockerfiles, not for running regression tests.

**Pull request merged**
