### PR TITLE
chore: update authors in .mailmap

### PR DESCRIPTION
**Pull request by tpgxyz**
This pull request removes duplicated my email in AUTHORS files

## Checklist
- [x] I have tested it locally
- [x] I have reviewed and updated any documentation if relevant
- [] I am providing new code and test(s) for it

### CODE REVIEW

**Comment by haraldh** [comment]
Please modify `.mailmap` instead, as `AUTHORS` is automatically generated from the git commits

**Comment by tpgxyz** [comment]
@haraldh done

**Review by johannbg — CHANGES_REQUESTED** [review]
You need to fix your commit message to pass the commisery check. Change it to "fix: update authors in .mailmap" . Drop the changes you made to the Author files as @haraldh has already pointed out that the file is automatically generated from the git commits, which means any manual changes to the file will get overwritten...

**Comment by haraldh** [comment]
it's more like 'chore:' than 'fix:' as it does not fix dracut

**Comment by johannbg** [comment]
@haraldh he's fixing his email addresses and he does so by adding himself to the authors in .mailmap file, that's a fix not a chore If he had already existed in the .mailmap file and then update it, it would have been a chore: instead of a fix: I would say. I also argue that fixes cover the entire tree not just dracut but either way it beats "remove duplicate me" and passes the commisery check so meh.

**Comment by haraldh** [comment]
Ok, then more like `docs: update authors in .mailmap`

**Comment by johannbg** [comment]
mailmap files aren't documentation so that makes no sense but if we break this action down all we are effectively doing there, is modifying the visual output of commands like git shortlog or git log --use-mailmap as in we are not rewriting commit history or prevent commits with varying names and/or email addresses and that action can be a done as a part of a chore as you pointed out or part of a fix ( which is the case what he arguably is doing or it could be a fix of incorrect entries in the file itself ). 

Anyway @tpgxyz just use chore since @haraldh feels strongly about it, we can run a script that detects and updates this as a part of a chore: which makes it more future proof and inline with what he proposes I guess.

**Comment by tpgxyz** [comment]
@haraldh @johannbg please forgive the inconvenience that I made. Hope it is fixed for good.

**Comment by johannbg** [comment]
@tpgxyz actually you have an extra whitespace between "in  .mailmap" so it's not "fixed" I mean chored :smile:  also change it to chore: which is better suited than docs + this no inconvenience, we just recently adopted and introduced commisery checks so we are still hashing out the details among ourselves.

**Comment by johannbg** [comment]
@tpgxyz you forgot to remove the extra whitespace as in "chore: update authors in<you have an extra whitespace here> .mailmap" which is triggering the commisery check to fail.

**Review by johannbg — APPROVED** [review]

**Review by haraldh — APPROVED** [review]

**Pull request merged**
