### PR TITLE
Introduce "rd.memdebug=4" to test kernel module memory consumption

### PR DESCRIPTION
**Pull request by xlpang**
1. Add memtrace-ko.sh to debug kernel module large memory consumption, installed as an   executable named "tracekomem"
2. Extend "rd.memdebug" to "4", and "make_trace_mem" to "4+:komem".
3. Update the dracut.cmdline manpage.
4. Add test for rd.memdebug

### CODE REVIEW

**Comment by haraldh** [comment]
@centos-ci 
ok to test

**Comment by xlpang** [comment]
Does that mean the last patch broke the CI test?
testsuite: add "rd.memdebug=4" in TEST-01-BASIC to test rd.memdebug

I wanted to add a test case for it, but seems it was the wrong way.

**Comment by haraldh** [comment]
@centos-ci
retest this please

**Comment by haraldh** [comment]
@centos-ci
retest this please

**Comment by haraldh** [comment]
@centos-ci
retest this please

**Comment by xlpang** [comment]
There are "    95ssh-client: attempt to copy UserKnownHostsFile to kdump's initramfs (detail / githubweb)" in the failed log. Wonder if the previous wrong PR affected this one. Let me try to re-request.

**Pull request closed without merging**
