### PR TITLE
fix(iscsi): several fixes for iscsi root

### PR DESCRIPTION
**Pull request by tblume**
This pull request changes...

## Checklist
- [x ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

### CODE REVIEW

**Review by johannbg — APPROVED** [review]
LGTM

**Comment by haraldh** [comment]
Please change the text of the commit message and describe why you are doing the change you are doing.

**Review by haraldh — COMMENTED** [review]
Please change the git commit message and describe why you doing the changes you did.

**Review by haraldh — CHANGES_REQUESTED** [review]
Please change the git commit message and describe why you doing the changes you did.

**Comment by tblume** [comment]
> Please change the git commit message and describe why you doing the changes you did.

The patch came from the SUSE open-iSCSI maintainer.
I've asked him for some more background.
I will update the commit message as soon as I get it.

**Comment by johannbg** [comment]
@tblume or you can just update the commit msg with the comments in your patch since those are quite clear as in `adding support for the new iscsiadm command that supports the "no-wait" (-W) flag` should suffice.

**Comment by tblume** [comment]
> @tblume or you can just update the commit msg with the comments in your patch since those are quite clear as in `adding support for the new iscsiadm command that supports the "no-wait" (-W) flag` should suffice.

Thanks, for the hint, I've also added a description for the second change.
Hope that is sufficient.

**Review by haraldh — APPROVED** [review]

**Pull request merged**
