### PR TITLE
All FCOE-related SUSE patches, rebased on top of master

### PR DESCRIPTION
**Pull request by danimo**
Mostly fixes. Some new features and command line/boot arguments.

### CODE REVIEW

**Comment by haraldh** [comment]
@centos-ci please test this

**Comment by haraldh** [comment]
@centos-ci ok to test

**Comment by haraldh** [comment]
modules.d/95fcoe/fcoe-up.sh: line 107: syntax error: unexpected end of file

**Comment by danimo** [comment]
Whoops, I'll fix that once I'm back on a machine.

**Comment by danimo** [comment]
@haraldh fixed

**Pull request merged**
