### PR TITLE
fix the breakpoint failure before swtich_root in centos 8.2

### PR DESCRIPTION
**Pull request by linux-gcc**
1、fix the breakpoint failure before swtich_root in centos 8.2;
2、whel the system starts with the rd.break parameter,the system cannot stop before ;
3、fix patch: dadfdc0

### CODE REVIEW

**Comment by linux-gcc** [comment]
can you take the time help review the code  ? dadfdc0
@haraldh @ryncsn @johannbg @danimo @lnykryn

**Comment by linux-gcc** [comment]
can you take the time help review the code ? dadfdc0
@dtardon 

thanks !

**Comment by linux-gcc** [comment]
1、 can you help review this code? dadfdc0
2、I have committed the bugzilla.
     bugzilla url: https://bugzilla.redhat.com/show_bug.cgi?id=1896591 
     
@haraldh @lnykryn

**Comment by dtardon** [comment]
@linux-gcc please stop pinging random people.

**Comment by linux-gcc** [comment]
what should  I do with this PR ?  looking forward to your reply. thanks !
@haraldh

**Comment by haraldh** [comment]
So, you want to revert 556ff7c76a5c365889ea9972c1878eaf7073bde8 ..

Specifying `rd.break` on the kernel command line will halt dracut just fine at this point.
You can even specify `rd.break=cleanup rd.break` and it halt in the cleanup phase and just before switch_root.

Seems to work for me, and other didn't report anything similar in the last 4 years.

**Comment by linux-gcc** [comment]
First of all, thank you very much for your reply！
 1、It means that there is a difference in the breakpoint function usage of initramfs between centos 7.x and centos 8.x?
 2、The centos 7.x series should not incorporate this patch,（556ff7c ）， so this issue should not have been reported in the last 4 years.
 3、In addition, what is the purpose of incorporating this patch before incorporating it?
@haraldh

**Pull request closed without merging**
