### PR TITLE
fix(cpio): test and fix dev_t -> rmajor / rminor mapping

### LINKED ISSUE #1695: dracut-cpio extracts device maj/min incorrectly
**Describe the bug**
`dracut-cpio`'s code to extract `major` and `minor` from a `dev_t` (obtained from `std::os::unix::fs::MetadataExt.rdev()`) is incorrect:
https://github.com/dracutdevs/dracut/blob/fe8df0240a24b9d2d60a5b0b998f82b251ede849/src/dracut-cpio/src/main.rs#L365-L366

The correct structure is:
https://github.com/bminor/glibc/blob/5b8e7980c5dabd9aaefeba4f0208baa8cf7653ee/bits/sysmacros.h#L26-L34
https://github.com/nix-rust/nix/blob/5cd01a1fd7417ee6e16636443965c0a197ff2843/src/sys/stat.rs#L72-L93

### PR DESCRIPTION
**Pull request by ddiss**
This pull request fixes dracut-cpio's `dev_t` -> `rmajor` / `rminor` mapping so that block devices, etc. are correctly encoded in the cpio archive.

## Checklist
- [x] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [x] I am providing new code and test(s) for it

Fixes #1695

### CODE REVIEW

**Comment by ddiss** [comment]
@ethanwu10 @aafeijoo-suse any feedback here? Thanks

**Review by ethanwu10 — APPROVED** [review]
lgtm

**Comment by aafeijoo-suse** [comment]
Sorry @ddiss, @johannbg, I didn't know you were waiting for my review, as my knowledge of Rust is close to zero and I hadn't tried the dracut-cpio stuff yet.

I can say this change looks good:
https://github.com/dracutdevs/dracut/blob/2f7e8b3ec0caa95f2d8bee0224a50731546b5eb1/src/dracut-cpio/src/main.rs#L367-L369

I also ran the tests an they returned the expected result, but I cannot say anything more about the code itself.

**Comment by ddiss** [comment]
> Sorry @ddiss, @johannbg, I didn't know you were waiting for my review, as my knowledge of Rust is close to zero and I hadn't tried the dracut-cpio stuff yet.
> 
> I can say this change looks good:
...
> I also ran the tests an they returned the expected result, but I cannot say anything more about the code itself.

No problem, Antonio. Thanks for taking a look :-)

**Review by johannbg — APPROVED** [review]

**Pull request merged**
