### PR TITLE
Remove obsolete test dependencies

### PR DESCRIPTION
**Pull request by danimo**
net-tools are not required anymore.

Tested on F25 with package removed.

### CODE REVIEW

**Comment by danimo** [comment]
ok to test

**Comment by danimo** [comment]
@centos-ci ok to test

**Comment by danimo** [comment]
This patch also drops the dependency on bridge-utils, by replacing them with calls to "ip". Allthough the "bridge" binary is not strictly needed, I added it instead. I can also drop it as it currently serves no purpose.

**Comment by danimo** [comment]
This patch also drops the dependency on bridge-utils, by replacing them with calls to "ip".

**Comment by haraldh** [comment]
@centos-ci ok to test

**Comment by danimo** [comment]
@centos-ci retest this please

**Comment by danimo** [comment]
Not sure what to make of that. Tests 30 and 50 succeed locally.

**Pull request merged**
