### PR TITLE
Adapt to the new udevadm version output

### PR DESCRIPTION
**Pull request by jsynacek**
See https://bugzilla.redhat.com/show_bug.cgi?id=1804252.

RHEL-only

Resolves: #1846034

### CODE REVIEW

**Comment by jsynacek** [comment]
The failed tests seem to be unrelated. The patch is backwards compatible as it simply "clamps" the output of `udevadm --version` in case it has more than one field.

**Comment by haraldh** [comment]
Instead of `cut` pure shell can be used..  `bin/cut` is not even installed

**Comment by danimo** [comment]
Out of interest: why is this RHEL only?

**Comment by lnykryn** [comment]
@danimo we patched systemd to contain release:
[root@ci-vm-10-0-138-178 ~]# udevadm --version
239 (239-33.el8)

**Comment by jsynacek** [comment]
> Instead of `cut` pure shell can be used.. `bin/cut` is not even installed

Well...
```
$ git grep '\Wcut\W'
dracut-init.sh:    if ! command -v kmod &>/dev/null && vercmp "$(modprobe --version | cut -d' ' -f3)" lt 3.7; then
dracut.sh:        _isize_new=$(du -sk ${initdir}|cut -f1)
modules.d/90kernel-modules-extra/module-setup.sh:		| sort -u -k1,1 -t '/' | cut -f 2- -d '/'))
modules.d/95iscsi/module-setup.sh:    for iface_desc in $(iscsiadm -m iface | cut -f 2 -d ' '); do
```

**Comment by jsynacek** [comment]
v2.

**Comment by haraldh** [comment]
> > Instead of `cut` pure shell can be used.. `bin/cut` is not even installed
> 
> Well...
> 
> ```
> $ git grep '\Wcut\W'
> dracut-init.sh:    if ! command -v kmod &>/dev/null && vercmp "$(modprobe --version | cut -d' ' -f3)" lt 3.7; then
> dracut.sh:        _isize_new=$(du -sk ${initdir}|cut -f1)
> modules.d/90kernel-modules-extra/module-setup.sh:		| sort -u -k1,1 -t '/' | cut -f 2- -d '/'))
> modules.d/95iscsi/module-setup.sh:    for iface_desc in $(iscsiadm -m iface | cut -f 2 -d ' '); do
> ```

`module-setup.sh` is executed while building the initramfs image.

**Pull request merged**
