### PR TITLE
Add --uefi-output for custom output filename

### LINKED ISSUE #921: Customize output filename
Hello!

I am generating an UEFI application using dracut and for now that one is automatically installed on the system, however that is not what I want, I would just want the UEFI application to be written somewhere so I can do what I have to do with it later.

The manual says:

> The default output filename is <EFI>/EFI/Linux/linux-$kernel$-<MACHINE_ID>-<BUILD_ID>.efi. <EFI> might be /efi, /boot or /boot/efi depending on where the ESP partition is mounted. The <BUILD_ID> is taken from BUILD_ID in /usr/lib/os-release or if it exists /etc/os-release and is left out, if BUILD_ID is non-existant or empty.

I would like not to use the default, it says it's default but that means it should be possible to not use the default?

How could I modify the output filename?

Thank you

### PR DESCRIPTION
**Pull request by leo-lb**
Closes #921

This pull request adds support for an `--uefi-output` command line parameter and an `uefi_output` configuration directive.

## Checklist
- [x] I have tested it locally
- [x] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

### CODE REVIEW

**Comment by leo-lb** [comment]
Do we need unit tests for this? I have tested it locally and it runs fine.

**Comment by leo-lb** [comment]
Does this need unit tests? I have tested it locally in these cases:

- [x] `--uefi-output` command line parameter present, all others absent
- [x] `uefi_output` configuration directive present, all others absent
- [x] all new options absent

And it works fine.

**Comment by leo-lb** [comment]
Failing tests look to be unrelated with this PR

**Comment by leo-lb** [comment]
@ryncsn I see you've accidentally unchecked some checkbox in my first post :-)

What would be missing for a review? I see there's a good amount of outstanding issues and PRs

**Review by danimo — CHANGES_REQUESTED** [review]
sorry for the late reply. Looks good, but can you add the parameter to dracut-bash-completion.sh as well?

**Comment by leo-lb** [comment]
@danimo Thanks for the review, I made the change you requested!

**Comment by danimo** [comment]
@haraldh what's the attribution policy?

**Comment by haraldh** [comment]
> @haraldh what's the attribution policy?

What do you mean?

**Comment by haraldh** [comment]
> @haraldh what's the attribution policy?

@danimo what do you mean?

**Comment by danimo** [comment]
> > @haraldh what's the attribution policy?
> @danimo what do you mean?

The patch adds the author's name to the man pages, and I realized that we have no real attribution policy there.

**Comment by haraldh** [comment]
> > > @haraldh what's the attribution policy?
> > > @danimo what do you mean?
> 
> The patch adds the author's name to the man pages, and I realized that we have no real attribution policy there.

Yeah, it shouldn't do that, unless the author belongs to the top committers.

Rule of thumb: running `make AUTHORS; head -n 10  AUTHORS` would output those.

**Comment by haraldh** [comment]
Or we just point to the shipped `AUTHORS` file.

**Comment by leo-lb** [comment]
I added it because I saw quite a few names there and that I edited the manual. To me that was the manual's authors, not the software authors.

**Comment by danimo** [comment]
Iet's update the authors file as part of the release process.

**Comment by leo-lb** [comment]
Thank you for merging, feel free to remove my name in the manual if that's not OK with you.

**Comment by barmadrid** [comment]
@danimo please review [this](https://github.com/dracutdevs/dracut/issues/921#issuecomment-733838751) and confirm if this merge should be reverted. Thank you!

**Pull request merged**
