### PR TITLE
feat(network-legacy): send dhcp in parallel on all devices

### PR DESCRIPTION
**Pull request by anjalidk**
We can drastically improve boot times on some machines, or BM or VM
shapes, if we send DHCP requests in parallel on all interfaces
Add ip=single-dhcp as a kernel boot parameter, to send DHCP requests in
parallel on all interfaces. Thus, DHCP on each interface is overlapped
thereby reducing boot times for multiple interface machines.
This can help reduce the boot time by 1 minute per interface.
In addition, we may also save another 40 secs delay per interface, if
the link on which we try to send DHCP is in DOWN state. This can be
reduced by giving the following kernel command line parameter while
booting - rd.net.timeout.carrier=<timeout>.
Added manpage for ip=single-dhcp with the caveat that it does not
apply to Network Manager or SUSE wicked.

Signed-off-by: Anjali Kulkarni <anjali.k.kulkarni@oracle.com>

This pull request changes...

## Checklist
- [x ] I have tested it locally
- [x ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

### CODE REVIEW

**Comment by anjalidk** [comment]
@johannbg @haraldh @danimo this branch parallel-dhcp-2 has exactly same change as old parallel-dhcp branch - and commisery errors are resolved - could you review/approve this one?

**Review by johannbg — APPROVED** [review]

**Comment by johannbg** [comment]
@anjalidk could you update your branch ( Let's see if test 99 wont succeed then )

**Comment by anjalidk** [comment]
@johannbg Looks like test case 30 and 35 failed now. 99 has passed.

**Comment by johannbg** [comment]
@anjalidk looks like the backend storage device is full. Dont worry about those tests.

**Review by haraldh — APPROVED** [review]

**Comment by anjalidk** [comment]
thanks all for your review, approval and merge into master!

**Pull request merged**
