### PR TITLE
feat(gensplash): remove module

### PR DESCRIPTION
**Pull request by LaszloGombos**
splashutils Gentoo package (a dependency for the gensplash dracut module)
is non existent in the official Gentoo repositories.

## Checklist
- [X] I have tested it locally
- [X] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

### CODE REVIEW

**Comment by johannbg** [comment]
So you want to remove a module just because the component for it does not exist in Gentoo? Have you checked if the module is not being used by other distro's or if upstream is inactive?

**Review by johannbg — APPROVED** [review]
Ok so I've looked into it and afaikt it looks like a dead project which no one else is using. 
Let's allow this to bake here for a couple of days to see if anyone objects the modules removal.

**Comment by LaszloGombos** [comment]
> Ok so I've looked into it and afaikt it looks like a dead project which no one else is using.
Thanks.

> Let's allow this to bake here for a couple of days to see if anyone objects the modules removal.
Make sense.

For the benefit of other readers - https://wiki.gentoo.org/wiki/Fbsplash

**Comment by johannbg** [comment]
Note that splash is still supported in gentoo's gen kernel  [gen_configkernel](https://gitweb.gentoo.org/proj/genkernel.git/tree/gen_configkernel.sh?id=6421096929ebe8819fa0edeaa80d1496f802ff6f#n196), [gen_initramfs](https://gitweb.gentoo.org/proj/genkernel.git/tree/gen_initramfs.sh?id=6421096929ebe8819fa0edeaa80d1496f802ff6f#n566), [gen_determineargs](https://gitweb.gentoo.org/proj/genkernel.git/tree/gen_determineargs.sh?id=6421096929ebe8819fa0edeaa80d1496f802ff6f#n97)
which is a bit weird since it's been deprecated in gentoo and propably trigger some errors if SPLASH="no" is not set in genkernel.conf so for whatever reason gentoo did not remove the support for it in gen kernel when the component got removed from the distro.

**Comment by johannbg** [comment]
@floppym note we are about to drop this module not sure if it will affect gentoo since weirdly enough genkernel still seemingly supports splash.

**Comment by johannbg** [comment]
A week has passed and no one screamed hence merging...

**Pull request merged**
