### PR TITLE
ci: upgrade to actions/checkout@v3

### PR DESCRIPTION
**Pull request by LaszloGombos**
It resolves the following warning:
Please update the following actions to use Node.js 16: actions/checkout

### CODE REVIEW

**Review by johannbg — APPROVED** [review]
LGTM

**Review by Conan-Kudo — APPROVED** [review]

**Review by iammattcoleman — APPROVED** [review]

**Comment by johannbg** [comment]
Maybe we should have dependabot handle this CI task for us in the future ( or implement it and see it working )
1. https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

**Comment by iammattcoleman** [comment]
@johannbg Is it possible to configure dependabot to _not_ upgrade some tests? In order to get the manual tests working in the Gentoo container, I had to revert to actions/checkout@v1 in this commit:
https://github.com/dracutdevs/dracut/commit/ef9ccd54467ea32d65b34206de73741bd938001f

This is due to version v2+ of the runner using a hardcoded path for an externally-provided node binary, but the provided binary not being compatible with Gentoo:
https://github.com/actions/runner/issues/2115

**Comment by johannbg** [comment]
@iammattcoleman it has allow/ignore: see [1] not sure if it works thou but honestly if gentoo is becoming too much trouble than it's worth and a security risk then we simply drop it and focus on something that costs less and makes our lives easier.

1. https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow

**Comment by LaszloGombos** [comment]
Marked as draft in favor of testing https://github.com/dracutdevs/dracut/pull/2016 .

**Comment by LaszloGombos** [comment]
Closing to take it out from active PR list. Will reopen if it becomes necessary.

**Comment by LaszloGombos** [comment]
Reopening for review

**Comment by johannbg** [comment]
Let's merge this and close the other one

**Comment by LaszloGombos** [comment]
@aafeijoo-suse Would you be able to help with the review of this PR ?

**Comment by aafeijoo-suse** [comment]
> @aafeijoo-suse Would you be able to help with the review of this PR ?

I don't know how I can help review this change, I'm not an expert on GitHub proprietary stuff and most of the time it just shows issues after the merge.

**Comment by LaszloGombos** [comment]
> and most of the time it just shows issues after the merge.

This is a fair statement. Please note:

 - https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
  - The way I read this is that around "Summer 2023" our CI might stop because of this..So there is plenty of time
   - I found a way to do a test run for this change - https://github.com/LaszloGombos/dracut/actions/runs/3445182730/jobs/5748600774 (note the "Run actions/checkout@v3" step)
    - If somehow there is still an issue after the merge, revert is always an option...
    
So the decision really is try to land or wait until it will be broken for sure..

**Review by aafeijoo-suse — APPROVED** [review]

**Pull request merged**
