### PR TITLE
Conceal ftp user passwd in rdsosreport

### PR DESCRIPTION
**Pull request by joeuo**
When using authenticated FTP, the password contained in the kernel command line.
This causes it to end up in the generated /run/initramfs/rdsosreport.txt

Signed-off-by: Zhiguo Deng bjzgdeng@linux.vnet.ibm.com

### CODE REVIEW

**Comment by haraldh** [comment]
What about all the other sensitive information? iSCSI passwords? Shouldn't the file be reviewed before submitted anyway?

**Comment by joeuo** [comment]
[Conceal-user-passwd-in-rdsosreport.txt](https://github.com/haraldh/dracut/files/36315/Conceal-user-passwd-in-rdsosreport.txt)
When using rd.cmdline=ask and supplying credential parameters from dracut shell, these infos will appear in /etc/cmdline.d/*.conf.  
The patch in attachment is another way of concealing passwords. However, this might be rough. 
For example, the iscsi allows multiple options, due to the greed match nature of sed, then only one
option will be showed in the rdsosreport.
The accurate way of concealing passwords could be parsing, substitution, and then reconstructing the cmdline, like sourcing 'dracut-lib',etc.   And for dmesg and journalctl, this may be a lot of work.

**Comment by haraldh** [comment]
ok to test

**Comment by haraldh** [comment]
@centos-ci 
ok to test

**Pull request closed without merging**
