### PR TITLE
feat(nbd): support ipv6 link local nbds

### PR DESCRIPTION
**Pull request by TheJJ**
For https://github.com/SFTtech/stiefelsystem we use NBD over IPv6-linklocal. This was not supported in dracut.

## Changes
* Add v6 linklocal support for network module (already upstream in network manager)
* Add v6 support for NBD
* Some minor fixes discovered along the way

## Checklist
- [x] I have tested it locally
- [x] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

### CODE REVIEW

**Comment by TheJJ** [comment]
One thing I'd like to also fix is the root switch using systemd when / is on NBD. Currently this somehow disconnects the nbd and then results in IO errors.

**Comment by johannbg** [comment]
> One thing I'd like to also fix is the root switch using systemd when / is on NBD. Currently this somehow disconnects the nbd and then results in IO errors.

If you haven't already you might want to go through [1][2] as as starting point for that fix.

1. https://systemd.io/ROOT_STORAGE_DAEMONS/
2. https://systemd.io/INITRD_INTERFACE/

**Comment by TheJJ** [comment]
Hm that's weird, I use `nbd-client -systemd-mark`, which should do exactly this and set `argv[0][0] = '@'`. But it seems to be killed anyway.

**Comment by johannbg** [comment]
> Hm that's weird, I use `nbd-client -systemd-mark`, which should do exactly this and set `argv[0][0] = '@'`. But it seems to be killed anyway.

Noticed that you have removed one of the ```-``` as in in your PR you change ```--systemd-mark``` to ```-systemd-mark``` could that be the root cause?

**Comment by johannbg** [comment]
@TheJJ also see https://github.com/NetworkBlockDevice/nbd/issues/91 upstream recently change their systemd type units.

**Comment by johannbg** [comment]
> > Hm that's weird, I use `nbd-client -systemd-mark`, which should do exactly this and set `argv[0][0] = '@'`. But it seems to be killed anyway.
> 
> Noticed that you have removed one of the `-` as in in your PR you change `--systemd-mark` to `-systemd-mark` could that be the root cause?

Just went upstream and through the code and ```-systemd-mark``` is correct ```--systemd-mark``` was incorrect so ignore this.

**Comment by johannbg** [comment]
@TheJJ maybe we should move this out of draft, review and merge and deal with the switch root issue in a separate PR or is there something else keeping this in draft mode?

**Comment by TheJJ** [comment]
Indeed we can review/merge it, I'll remove the changed systemd-parts for now.

**Review by johannbg — APPROVED** [review]
LGTM

**Review by haraldh — APPROVED** [review]

**Pull request merged**
