### PR TITLE
fix(dracut-install): do not try to copy files from the root directory

### PR DESCRIPTION
**Pull request by marcosfrm**
@dtardon
@lnykryn

Can you have a look?

### CODE REVIEW

**Review by dtardon — APPROVED** [review]
LGTM

**Comment by marcosfrm** [comment]
Force-pushed new version to silence the linter. No functional changes.

**Comment by pvalena** [comment]
LGTM.

**Review by lnykryn — APPROVED** [review]

**Comment by lnykryn** [comment]
LGTM as well

**Review by johannbg — APPROVED** [review]
LGTM

**Pull request merged**
